### ISSUE TITLE
Hardware (gesponsort)

### ISSUE THREAD

**Issue by AlbertUnruh** [Projects-At-GP/Wetterballon-22-Hardware#1]
Ich könnte folgendes anbieten was wir gesponsort bekommen könnten:

| Sensor                           | Produkt                                     |
|----------------------------------|---------------------------------------------|
| Funkmodul                        | [LoRIS-BASE][1]                             |
| GPS                              | [muss ich noch finden...][2]                |
| Temperatur/Feuchte               | [Sensirion SHT20][3]                        |
| CO2                              | [Senseair Sunrise][4]                       |
| Lichtsensor                      | [Texas Instruments OPT3001][5]              |
| Gyroskop & Beschleunigungssensor | [MPU-6050][6] / [CRIUS MultiWii SE v0.2][7] |

> Woher die kommen? Liegen noch zuhause rum ^^

[1]: https://de.elv.com/loris-base-funk-basismodul-1-loris-bm-trx1-156514
[2]: # "Produkt ID momentan unbekannt"
[3]: https://sensirion.com/de/produkte/katalog/SHT20/
[4]: https://senseair.com/products/power-counts/sunrise/
[5]: https://www.ti.com/product/OPT3001
[6]: https://invensense.tdk.com/products/motion-tracking/6-axis/mpu-6050/
[7]: # "kein Shop mehr verfügbar"

**Comment by AlbertUnruh** [comment]
@Projects-At-GP/mint-wetterballon-22 gibt es dafür Verwendung?

**Comment by CC35A** [comment]
> @Projects-At-GP/mint-wetterballon-22 gibt es dafür Verwendung?

jo, habe es bereits in [sensorik.md](../blob/main/Sensorik.md) eingefügt.
